import type { Currency } from './types';

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'United States Dollar', countryCode: 'us' },
  { code: 'EUR', name: 'Euro', countryCode: 'eu' },
  { code: 'JPY', name: 'Japanese Yen', countryCode: 'jp' },
  { code: 'GBP', name: 'British Pound Sterling', countryCode: 'gb' },
  { code: 'AUD', name: 'Australian Dollar', countryCode: 'au' },
  { code: 'CAD', name: 'Canadian Dollar', countryCode: 'ca' },
  { code: 'CHF', name: 'Swiss Franc', countryCode: 'ch' },
  { code: 'CNY', name: 'Chinese Yuan', countryCode: 'cn' },
  { code: 'SEK', name: 'Swedish Krona', countryCode: 'se' },
  { code: 'NZD', name: 'New Zealand Dollar', countryCode: 'nz' },
  { code: 'MXN', name: 'Mexican Peso', countryCode: 'mx' },
  { code: 'SGD', name: 'Singapore Dollar', countryCode: 'sg' },
  { code: 'HKD', name: 'Hong Kong Dollar', countryCode: 'hk' },
  { code: 'NOK', name: 'Norwegian Krone', countryCode: 'no' },
  { code: 'KRW', name: 'South Korean Won', countryCode: 'kr' },
  { code: 'TRY', name: 'Turkish Lira', countryCode: 'tr' },
  { code: 'RUB', name: 'Russian Ruble', countryCode: 'ru' },
  { code: 'INR', name: 'Indian Rupee', countryCode: 'in' },
  { code: 'BRL', name: 'Brazilian Real', countryCode: 'br' },
  { code: 'ZAR', name: 'South African Rand', countryCode: 'za' },
  { code: 'AED', name: 'UAE Dirham', countryCode: 'ae' },
  { code: 'AFN', name: 'Afghan Afghani', countryCode: 'af' },
  { code: 'ALL', name: 'Albanian Lek', countryCode: 'al' },
  { code: 'AMD', name: 'Armenian Dram', countryCode: 'am' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', countryCode: 'sx' },
  { code: 'AOA', name: 'Angolan Kwanza', countryCode: 'ao' },
  { code: 'ARS', name: 'Argentine Peso', countryCode: 'ar' },
  { code: 'AWG', name: 'Aruban Florin', countryCode: 'aw' },
  { code: 'AZN', name: 'Azerbaijani Manat', countryCode: 'az' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', countryCode: 'ba' },
  { code: 'BBD', name: 'Barbadian Dollar', countryCode: 'bb' },
  { code: 'BDT', name: 'Bangladeshi Taka', countryCode: 'bd' },
  { code: 'BGN', name: 'Bulgarian Lev', countryCode: 'bg' },
  { code: 'BHD', name: 'Bahraini Dinar', countryCode: 'bh' },
  { code: 'BIF', name: 'Burundian Franc', countryCode: 'bi' },
  { code: 'BMD', name: 'Bermudian Dollar', countryCode: 'bm' },
  { code: 'BND', name: 'Brunei Dollar', countryCode: 'bn' },
  { code: 'BOB', name: 'Bolivian Boliviano', countryCode: 'bo' },
  { code: 'BSD', name: 'Bahamian Dollar', countryCode: 'bs' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', countryCode: 'bt' },
  { code: 'BWP', name: 'Botswanan Pula', countryCode: 'bw' },
  { code: 'BYN', name: 'Belarusian Ruble', countryCode: 'by' },
  { code: 'BZD', name: 'Belize Dollar', countryCode: 'bz' },
  { code: 'CDF', name: 'Congolese Franc', countryCode: 'cd' },
  { code: 'CLP', name: 'Chilean Peso', countryCode: 'cl' },
  { code: 'COP', name: 'Colombian Peso', countryCode: 'co' },
  { code: 'CRC', name: 'Costa Rican Colón', countryCode: 'cr' },
  { code: 'CUP', name: 'Cuban Peso', countryCode: 'cu' },
  { code: 'CVE', name: 'Cape Verdean Escudo', countryCode: 'cv' },
  { code: 'CZK', name: 'Czech Koruna', countryCode: 'cz' },
  { code: 'DJF', name: 'Djiboutian Franc', countryCode: 'dj' },
  { code: 'DKK', name: 'Danish Krone', countryCode: 'dk' },
  { code: 'DOP', name: 'Dominican Peso', countryCode: 'do' },
  { code: 'DZD', name: 'Algerian Dinar', countryCode: 'dz' },
  { code: 'EGP', name: 'Egyptian Pound', countryCode: 'eg' },
  { code: 'ERN', name: 'Eritrean Nakfa', countryCode: 'er' },
  { code: 'ETB', name: 'Ethiopian Birr', countryCode: 'et' },
  { code: 'FJD', name: 'Fijian Dollar', countryCode: 'fj' },
  { code: 'FKP', name: 'Falkland Islands Pound', countryCode: 'fk' },
  { code: 'FOK', name: 'Faroese Króna', countryCode: 'fo' },
  { code: 'GEL', name: 'Georgian Lari', countryCode: 'ge' },
  { code: 'GGP', name: 'Guernsey Pound', countryCode: 'gg' },
  { code: 'GHS', name: 'Ghanaian Cedi', countryCode: 'gh' },
  { code: 'GIP', name: 'Gibraltar Pound', countryCode: 'gi' },
  { code: 'GMD', name: 'Gambian Dalasi', countryCode: 'gm' },
  { code: 'GNF', name: 'Guinean Franc', countryCode: 'gn' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', countryCode: 'gt' },
  { code: 'GYD', name: 'Guyanaese Dollar', countryCode: 'gy' },
  { code: 'HNL', name: 'Honduran Lempira', countryCode: 'hn' },
  { code: 'HRK', name: 'Croatian Kuna', countryCode: 'hr' },
  { code: 'HTG', name: 'Haitian Gourde', countryCode: 'ht' },
  { code: 'HUF', name: 'Hungarian Forint', countryCode: 'hu' },
  { code: 'IDR', name: 'Indonesian Rupiah', countryCode: 'id' },
  { code: 'ILS', name: 'Israeli New Shekel', countryCode: 'il' },
  { code: 'IMP', name: 'Isle of Man Pound', countryCode: 'im' },
  { code: 'IQD', name: 'Iraqi Dinar', countryCode: 'iq' },
  { code: 'IRR', name: 'Iranian Rial', countryCode: 'ir' },
  { code: 'ISK', name: 'Icelandic Króna', countryCode: 'is' },
  { code: 'JEP', name: 'Jersey Pound', countryCode: 'je' },
  { code: 'JMD', name: 'Jamaican Dollar', countryCode: 'jm' },
  { code: 'JOD', name: 'Jordanian Dinar', countryCode: 'jo' },
  { code: 'KES', name: 'Kenyan Shilling', countryCode: 'ke' },
  { code: 'KGS', name: 'Kyrgystani Som', countryCode: 'kg' },
  { code: 'KHR', name: 'Cambodian Riel', countryCode: 'kh' },
  { code: 'KID', name: 'Kiribati Dollar', countryCode: 'ki' },
  { code: 'KMF', name: 'Comorian Franc', countryCode: 'km' },
  { code: 'KWD', name: 'Kuwaiti Dinar', countryCode: 'kw' },
  { code: 'KYD', name: 'Cayman Islands Dollar', countryCode: 'ky' },
  { code: 'KZT', name: 'Kazakhstani Tenge', countryCode: 'kz' },
  { code: 'LAK', name: 'Laotian Kip', countryCode: 'la' },
  { code: 'LBP', name: 'Lebanese Pound', countryCode: 'lb' },
  { code: 'LKR', name: 'Sri Lankan Rupee', countryCode: 'lk' },
  { code: 'LRD', name: 'Liberian Dollar', countryCode: 'lr' },
  { code: 'LSL', name: 'Lesotho Loti', countryCode: 'ls' },
  { code: 'LYD', name: 'Libyan Dinar', countryCode: 'ly' },
  { code: 'MAD', name: 'Moroccan Dirham', countryCode: 'ma' },
  { code: 'MDL', name: 'Moldovan Leu', countryCode: 'md' },
  { code: 'MGA', name: 'Malagasy Ariary', countryCode: 'mg' },
  { code: 'MKD', name: 'Macedonian Denar', countryCode: 'mk' },
  { code: 'MMK', name: 'Myanmar Kyat', countryCode: 'mm' },
  { code: 'MNT', name: 'Mongolian Tugrik', countryCode: 'mn' },
  { code: 'MOP', name: 'Macanese Pataca', countryCode: 'mo' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', countryCode: 'mr' },
  { code: 'MUR', name: 'Mauritian Rupee', countryCode: 'mu' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', countryCode: 'mv' },
  { code: 'MWK', name: 'Malawian Kwacha', countryCode: 'mw' },
  { code: 'MYR', name: 'Malaysian Ringgit', countryCode: 'my' },
  { code: 'MZN', name: 'Mozambican Metical', countryCode: 'mz' },
  { code: 'NAD', name: 'Namibian Dollar', countryCode: 'na' },
  { code: 'NGN', name: 'Nigerian Naira', countryCode: 'ng' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', countryCode: 'ni' },
  { code: 'NPR', name: 'Nepalese Rupee', countryCode: 'np' },
  { code: 'OMR', name: 'Omani Rial', countryCode: 'om' },
  { code: 'PAB', name: 'Panamanian Balboa', countryCode: 'pa' },
  { code: 'PEN', name: 'Peruvian Nuevo Sol', countryCode: 'pe' },
  { code: 'PGK', name: 'Papua New Guinean Kina', countryCode: 'pg' },
  { code: 'PHP', name: 'Philippine Peso', countryCode: 'ph' },
  { code: 'PKR', name: 'Pakistani Rupee', countryCode: 'pk' },
  { code: 'PLN', name: 'Polish Złoty', countryCode: 'pl' },
  { code: 'PYG', name: 'Paraguayan Guarani', countryCode: 'py' },
  { code: 'QAR', name: 'Qatari Riyal', countryCode: 'qa' },
  { code: 'RON', name: 'Romanian Leu', countryCode: 'ro' },
  { code: 'RSD', name: 'Serbian Dinar', countryCode: 'rs' },
  { code: 'RWF', name: 'Rwandan Franc', countryCode: 'rw' },
  { code: 'SAR', name: 'Saudi Riyal', countryCode: 'sa' },
  { code: 'SBD', name: 'Solomon Islands Dollar', countryCode: 'sb' },
  { code: 'SCR', name: 'Seychellois Rupee', countryCode: 'sc' },
  { code: 'SDG', name: 'Sudanese Pound', countryCode: 'sd' },
  { code: 'SHP', name: 'Saint Helena Pound', countryCode: 'sh' },
  { code: 'SLE', name: 'Sierra Leonean Leone', countryCode: 'sl' },
  { code: 'SOS', name: 'Somali Shilling', countryCode: 'so' },
  { code: 'SRD', name: 'Surinamese Dollar', countryCode: 'sr' },
  { code: 'SSP', name: 'South Sudanese Pound', countryCode: 'ss' },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', countryCode: 'st' },
  { code: 'SYP', name: 'Syrian Pound', countryCode: 'sy' },
  { code: 'SZL', name: 'Swazi Lilangeni', countryCode: 'sz' },
  { code: 'THB', name: 'Thai Baht', countryCode: 'th' },
  { code: 'TJS', name: 'Tajikistani Somoni', countryCode: 'tj' },
  { code: 'TMT', name: 'Turkmenistani Manat', countryCode: 'tm' },
  { code: 'TND', name: 'Tunisian Dinar', countryCode: 'tn' },
  { code: 'TOP', name: 'Tongan Paʻanga', countryCode: 'to' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', countryCode: 'tt' },
  { code: 'TWD', name: 'New Taiwan Dollar', countryCode: 'tw' },
  { code: 'TZS', name: 'Tanzanian Shilling', countryCode: 'tz' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', countryCode: 'ua' },
  { code: 'UGX', name: 'Ugandan Shilling', countryCode: 'ug' },
  { code: 'UYU', name: 'Uruguayan Peso', countryCode: 'uy' },
  { code: 'UZS', name: 'Uzbekistan Som', countryCode: 'uz' },
  { code: 'VES', name: 'Venezuelan Bolívar', countryCode: 've' },
  { code: 'VND', name: 'Vietnamese Dong', countryCode: 'vn' },
  { code: 'VUV', name: 'Vanuatu Vatu', countryCode: 'vu' },
  { code: 'WST', name: 'Samoan Tala', countryCode: 'ws' },
  { code: 'XAF', name: 'CFA Franc BEAC', countryCode: 'cm' },
  { code: 'XCD', name: 'East Caribbean Dollar', countryCode: 'ag' },
  { code: 'XDR', name: 'Special Drawing Rights', countryCode: 'un' },
  { code: 'XOF', name: 'CFA Franc BCEAO', countryCode: 'sn' },
  { code: 'XPF', name: 'CFP Franc', countryCode: 'pf' },
  { code: 'YER', name: 'Yemeni Rial', countryCode: 'ye' },
  { code: 'ZMW', name: 'Zambian Kwacha', countryCode: 'zm' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', countryCode: 'zw' },
];
